### ISSUE TITLE
Issue with August Processing

### ISSUE THREAD

**Issue by NickCEBM** [ebmdatalab/euctr-tracker-code#114]
@madwort Know you are away this week so just documenting so I don't forget anything until you are back.

Got the normalization email this month and was suspicious when the number was less than last month and there was only 1 trial to normalize:

July: 12829/12884

August: 11064/11065

I've done some investigation and it looks like a bunch of the scrape didn't work. Here is the distribution of the top of the`meta_updated` field for July:

![image](https://user-images.githubusercontent.com/25153969/129013469-42f406ee-ae0f-44bf-b7cd-b34fb681c83c.png)

And here it is for August:

![image](https://user-images.githubusercontent.com/25153969/129013518-d6fc25a4-75ec-4120-a87b-b5a664aebe2b.png)

So the scrape didn't work for just under 30% of trials seemed to fail and while not totally out of the realm of possibility (if the EMA is being slow over the summer), both raw datasets are the same length (102,458 rows)

I would think that would (generally) be fine as last month's version of those trials would just be used based on our "keep around disappearing trials for a bit" rules (we'd miss out on some updated information but at least it would work) but that appears to not be the case.

I did some comparison of the normalisation file for the 2 months and it looks like the missing records from August exist just fine on the EUCTR (on a random check of a few) so probably just went down mid-scrape and for some reason our post-processing threw out at least some (if not all) of those trials that never updated month-over-month and they never for to the normalisation process?

Probably just a case of re-running the scrape and hope we get luckier this time?

**Comment by madwort** [comment]
Nick's comment from PM

> here is a good example. the sponsor "3M" usually has three names associated with it across 3 trials. All are in the July and August raw scrape and exist on the EUCTR. 2004-003910-41 updated and is in the August norm spreadsheet but 2006-003211-40 and 2004-004654-19 did not update and are not in the August norm spreadsheet.
12:30
Those last 2 both last updated in the July scrape (so not super old and just lingering)

**Comment by madwort** [comment]
yeah, so it's definitely a regression/bug introduced in #109 
```
(venv) root@smallweb1:/var/www/eutrialstracker_live/euctr-tracker-code/euctr# ./manage.py get_trials_from_db -v 2
Late scrape start date: 2021-08-07
Will skip trials older than: 2021-08-06
Due date cutoff: 2020-07-10 00:00:00
```

the `Will skip trials older than` should be "at least 60 days and 2 scrapes" earlier than the "late (sic) scrape date"

**Comment by madwort** [comment]
after merging the above patch, re-ran get_trials_from_db - this resulted in an 18MB file (up from 14MB), which includes both 2006-003211-40 and 2004-004654-19. I therefore declare this issue resolved.
