### ISSUE TITLE
Bring website up to date with current data

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/euctr-tracker-code#36]
In other words, revert changes related to #29 and #30

**Comment by sebbacon** [comment]
Steps:
* Make a local backup of the `json` data files for easy rolling back
* Revert https://github.com/ebmdatalab/euctr-tracker-code/commit/49f53954b7c340d9936eaa5ee52daaa8cdb8ef1a
* Run loaddata-eutrialstracker_live.sh`
* Restart the server.
* See if it works. One reason it may not: the normalisation spreadsheet may need updating
* If there are problems, revert the data to an older version

**Comment by sebbacon** [comment]
So we get:
```
./manage.py update_trials_json
Trials CSV: 41989 / 42179 entries matched
Normalise CSV: 10972 / 11153 entries complete

NOT GOING LIVE, until all trials are matched.

See ../../euctr-tracker-data/new_trials.csv for trials requiring normalisation
```

(note that we should make the cron job output this info - I don't think it does)

**Comment by sebbacon** [comment]
@NickCEBM there needs to be a bit of normalisation to proceed with this:

[new_trials.zip](https://github.com/ebmdatalab/euctr-tracker-code/files/2262979/new_trials.zip)

**Comment by NickCEBM** [comment]
On this now that I'm back.
