### ISSUE TITLE
Additions and Updates to EU TrialsTracker

### ISSUE THREAD

**Issue by NickCEBM** [ebmdatalab/euctr-tracker-code#42]
We would like to add the following:

1.  Updated FAQ (Nick's responsibility)
2. A version of this for the EU website: https://fdaaa.trialstracker.net/fund/
3. A clear link to the paper at the top of the website like we did here: http://policyaudit.alltrials.net/

**Comment by sebbacon** [comment]
FAQ recorded in new issue #60
