### ISSUE TITLE
EUCTR scrape suspiciously fast

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/euctr-tracker-code#44]
It kicked off correctly on 1 September.

This morning, @NickCEBM  started getting emails once every 30 mins (below).

There are no commits in the data repo.

![image](https://user-images.githubusercontent.com/211271/46341940-74330d00-c631-11e8-80bb-089289619e2e.png)

**Comment by sebbacon** [comment]
The scraper log  at `/var/log/eutrialstracker_live/crawl-2018-09-30.log` exited with an error:

```
2018-10-01 18:58:44 [scrapy.core.scraper] ERROR: Error downloading <GET https://www.clinicaltrialsregister.eu/ctr-search/trial/2016-003325-41/AT>: [<twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>]
2018-10-01 18:58:44 [scrapy.core.engine] INFO: Closing spider (finished)
2018-10-01 18:58:44 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/exception_count': 816,
 'downloader/exception_type_count/twisted.web._newclient.ResponseNeverReceived': 816,
 'downloader/request_bytes': 40338660,
 'downloader/request_count': 86612,
 'downloader/request_method_count/GET': 86612,
 'downloader/response_bytes': 1110111949,
 'downloader/response_count': 85796,
 'downloader/response_status_count/200': 85733,
 'downloader/response_status_count/500': 63,
 'dupefilter/filtered': 3,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2018, 10, 1, 18, 58, 44, 696830),
 'item_scraped_count': 83852,
 'log_count/DEBUG': 254318,
 'log_count/ERROR': 13,
 'log_count/INFO': 86881,
 'memusage/max': 213504000,
 'memusage/startup': 70377472,
 'request_depth_max': 1669,
 'response_received_count': 85733,
 'retry/count': 866,
 'retry/max_reached': 13,
 'retry/reason_count/500 Internal Server Error': 63,
 'retry/reason_count/twisted.web._newclient.ResponseNeverReceived': 803,
 'scheduler/dequeued': 86612,
 'scheduler/dequeued/memory': 86612,
 'scheduler/enqueued': 86612,
 'scheduler/enqueued/memory': 86612,
 'start_time': datetime.datetime(2018, 10, 1, 1, 0, 4, 57823)}
2018-10-01 18:58:44 [scrapy.core.engine] INFO: Spider closed (finished)
```

**Comment by sebbacon** [comment]
1) It's not obvious when it *should* exit with an error code, per https://github.com/scrapy/scrapy/issues/1231

2) And thus it's not obvious it terminated early, in fact - is it chance that the last entry in the log was a 500?

**Comment by sebbacon** [comment]
Actually there were 64 500 errors. The code would appear to attempt to update those next time. I guess this is OK.

**Comment by sebbacon** [comment]
Apparently the scrape took 18 hours.  So it wasn't "suspiciously fast". Sometimes it takes 5 hours.

**Comment by sebbacon** [comment]
So I think there is no error, apart from we probably don't want it to run every 30 mins - daily is probably fine.

**Comment by NickCEBM** [comment]
So while there may not have been an issue with the scrape, there is an issue in that the scrape did not commit the `new_trial.csv` document to the `Data` repo. The last commit for that document remains 21 days ago so has not been replaced by this most recent scrape.

![image](https://user-images.githubusercontent.com/25153969/46356440-ac9b1100-c65a-11e8-8a2b-4b7fef47aa97.png)

**Comment by NickCEBM** [comment]
Also, still getting emails every hour.

**Comment by sebbacon** [comment]
@NickCEBM are you happy for me to change the reminder to daily? 

The downside is that you'll have to wait for up to 24 hours for the site to get updated following uploading the normalised sheet.

There are nicer possible solutions, but ones that require me to do more coding (e.g. could make it bot-controlled like FDAAA)

**Comment by sebbacon** [comment]
To explain further: that every-30-mins thing is *both* reminding you to do the spreadsheet *and* updating the website if it has been uploaded.

**Comment by NickCEBM** [comment]
Can we make it somewhere inbetween? Every 6 hours? I don't always get to the normalisation right away so every hour is a bit grating.
