### ISSUE TITLE
Date not on EUCTR persists in scrape.

### ISSUE THREAD

**Issue by NickCEBM** [ebmdatalab/euctr-tracker-code#53]
In mid-December, Bayer got in touch about two trials:

[2014-000565-47](https://www.clinicaltrialsregister.eu/ctr-search/search?query=2014-000565-47) and [2012-004857-10](https://www.clinicaltrialsregister.eu/ctr-search/search?query=2012-004857-10)

2014-000565-47 took place in 14 countries.

2012-004857-10 took places in 2 countries.

They noted that we have completion dates listed for these two trial on the EU TrialsTracker, that do not exist on the EUCTR. On investigation this was correct, these completion dates do not exist, currently, for any of the country protocols on the EUCTR.

![image](https://user-images.githubusercontent.com/25153969/50762639-71b20600-1265-11e9-951e-6a2754c6e5a1.png)

![image](https://user-images.githubusercontent.com/25153969/50762651-78d91400-1265-11e9-913c-a8ed4198fe21.png)

I went back and checked old EUCTR scrapes and there were completion dates for a single country for each trial.

Starting in our saved January 2018 scrape, and persisting through every other version we have archived, including the most recent January 2019 scrape, 2014-000565-47 has a completion date of 2017-04-05 for their Irish protocol (IE) and 2012-004857-10 has a completion date of 2016-09-28 for their German protocol (DE).

Because the EUCTR does not keep any versioning, we can’t tell if these completion dates did once exist but no longer exist, and if they changed when, however we can be sure they did not exist as of mid-December 2018 but showed up in the January 2019 scrape. I have asked Bayer if they know if/when the data for these trials has ever changed but have not gotten a response. 

Can run this query in BigQuery to see the new scrape:

```SQL
select 
eudract_number_with_country, 
date_of_the_global_end_of_the_trial, 
meta_updated 
from `euctr.euctr_2019_01` 
where regexp_contains(eudract_number, "2014-000565-47")
OR
regexp_contains(eudract_number, "2012-004857-10")
```

Compared to say, this query (from the November scrape):

```SQL
select 
eudract_number_with_country, 
date_of_the_global_end_of_the_trial, 
meta_updated 
from `euctr.euctr_2018_11` 
where regexp_contains(eudract_number, "2014-000565-47")
OR
regexp_contains(eudract_number, "2012-004857-10")
```

I have a hunch that the scraper we use for this, when it builds a database, builds it on top of the existing database with each scrape only changing the things that differ from the previous scrape and it may not do well handling places where there was data that is now null. This may have even been intentional?

**Comment by sebbacon** [comment]
Despite this code being deployed, a scrape from yesterday failed to produce any new data.

**Comment by sebbacon** [comment]
```
psycopg2.IntegrityError: null value in column "meta_created" violates not-null c
onstraint





Errors evident in the scraper log:

    sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) null value in column "meta_created" violates not-null constraint

And

    sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) null value in column "meta_updated" violates not-null constraint

**Comment by sebbacon** [comment]
Another scrape kicked off. Let's see if that works.
